### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by mbastian** [gephi/gexf#21]
I realised we don't specifically mention a license in this repository.

I suggest https://creativecommons.org/licenses/by/4.0/ but I'm open for suggestions

**Comment by mbastian** [comment]
@jacomyma @duncdrum @paulgirard @gvegayon @eduramiba @Yomguithereal

Any objections or suggestions? Thx

**Comment by duncdrum** [comment]
CC-BY makes sense and is a good choice

**Comment by jacomyma** [comment]
+1, CC-BY seems appropriate to me.

**Comment by paulgirard** [comment]
good to me too

**Comment by gvegayon** [comment]
I agree; this license looks good to me too.

**Comment by mbastian** [comment]
Excellent, thanks all for your input. I'll make the change
