### ISSUE TITLE
static datatypes and attributes

### ISSUE THREAD

**Issue by duncdrum** [gephi/gexf#3]
@mbastian  said
> * Add an optional edge kind attribute: This is the base of the property graph and defined some kind of label that defines the nature of the relationship. Unfortunately we already use type (for directed/undirected) and label (unique string for each edge) but "kind" seems clear enough.
* idtype: The current 1.2 specifications describe an idtype attribute one can set on graph to configure the type of element ids. This is actually something that we never implemented in the import/export and could now be done because GraphStore supports it. So I suggest to start supporting this and also add long in addition of string (default) and integer.
* slice mode: To make the distiction between dynamic graphs contained into a single GEXF (i.e. our current 'dynamic' mode) and dynamic graphs contained in a collection of GEXF files I suggest to introduce an additional 'mode' attribute names 'slice'. The possible values are currently 'static' (default) and 'dynamic'.
* Add a new “hex” attribute to viz:color: It would allow to use things like hex=“#FF00FF”. I would suggest to support alpha there as well.

**Comment by duncdrum** [comment]
slices aren't defined in the grammar yet, since i m not 100% clear on what they should do

**Comment by mbastian** [comment]
Slices are a way to characterize a complete `<graph>` over time and say something like "this graph is at that state at timestamp `t`. You can imagine the scenario where a researcher is making a snapshot of a given graph at regular periods. Each snapshot would then be a different GEXF file and I would call this snapshot a slice of the global over-time network. For gephi to allow the merge of these different GEXF files it needs to know when was this snapshot taken and that's the role of the `timestamp` attribute on `graph`. Alternatively, we allow to characterize a slice/snapshot with an interval.

**Comment by duncdrum** [comment]
ok got it, seem that the remaining work for slices depends on the commits on the other issue. Closing this one
