### ISSUE TITLE
depreciate hierarchical graphs?

### ISSUE THREAD

**Issue by duncdrum** [gephi/gexf#5]
but maybe find a way to allow backwards compatibility via hierarchy.rng

**Comment by mbastian** [comment]
I don't think we should deprecate hierarchical graphs. OK Gephi doesn't support them anymore at the moment but the door isn't closed for a future (better) implementation.

**Comment by duncdrum** [comment]
Ok. I ll open a new issue where we can gather some input on how to move forward with hierarchical graphs, once the current set of changes is implemented.
