### ISSUE TITLE
primer keep tex or move to wiki?

### ISSUE THREAD

**Issue by duncdrum** [gephi/gexf#6]
Now that we have a repo would it make sense to move the old pdf/tex primer materials into the repo's wiki?

**Comment by mbastian** [comment]
Yes I agree it would make sense. It would be easier to edit and I don't see anything we can do in tex that we can't do in the wiki. We should still make sure to version the documentation so I imagine one page per GEXF version is enough. We probably don't need to migrate old primers (<1.3) but start the work on the 1.3 primer on the wiki right away.

**Comment by duncdrum** [comment]
Great I ll get on it then

**Comment by duncdrum** [comment]
markdown files are in my fork

**Comment by mbastian** [comment]
This is awesome. I added you as a contributor to this repository. Can you try whether you can directly push and edit the wiki? Thanks!

**Comment by duncdrum** [comment]
Thanks for adding me, i need to run some more tests, before i ll push schema changes, i ll edit the wiki as i go along.
